---
engines:

  duplication:
    enabled: false
  govet:
    enabled: true
  golint:
    enabled: true
  nodesecurity:
    enabled: true
    exclude_fingerprints:
      - db2b925f6a46b556ffeaf17fa6a26952 https://github.com/hueniverse/hawk/issues/168
  eslint:
    enabled: false
  fixme:
    enabled: false
  csslint:
    enabled: false

ratings:
  paths:
  - "**.go"
  - "**.js"

exclude_paths:
  - static_src/test/*
  - helpers/*
  - acceptance/*
  - "**/*_test.go"
