---
engines:

  duplication:
    enabled: false
  govet:
    enabled: true
  golint:
    enabled: true
  nodesecurity:
    enabled: true
  eslint:
    enabled: false
  fixme:
    enabled: false
  csslint:
    enabled: false

ratings:
  paths:
  - "**.go"
  - "**.js"

exclude_paths:
  - static_src/test/*
