---
version: 2
plugins:
  govet:
    enabled: true
  golint:
    enabled: true
  nodesecurity:
    enabled: true
  eslint:
    enabled: false
  fixme:
    enabled: false
  csslint:
    enabled: false
    
checks:
  similar-code:
    enabled: false
  identical-code:
    enabled: false

exclude_patterns:
  - static_src/test/*
  - screenshots/
  - "**/node_modules/"
  - "**/spec/"
  - "**/tests/"
  - "**/vendor/"
  - static/bower_components/
  - static/assets/
  - .DS_Store/
  - helpers/debug.test

