---
engines:

  duplication:
    enabled: false
  govet:
    enabled: true
  golint:
    enabled: true
  nodesecurity:
    enabled: true
    exclude_fingerprints:
      - db2b925f6a46b556ffeaf17fa6a26952 https://github.com/hueniverse/hawk/issues/168
      - ccfee66849da0982a0bc703f19b3d57d tough-cookie ReDoS via long string of semicolons
  eslint:
    enabled: true
  fixme:
    enabled: false
  csslint:
    enabled: true

ratings:
  paths:
  - "**.go"
  - "**.js"

exclude_paths:
  - static_src/test/*
  - "**/*_test.go"
