language: go
sudo: required
go:
- 1.5
services:
  - docker
before_install:
- rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
- npm install
- npm run build
- pip install --user ruamel.yaml
- wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
- tar -xjf phantomjs-2.0.0-ubuntu-12.04.tar.bz2
- export PHANTOMJS_BIN=./phantomjs
script:
- npm test
- "./codecheck.sh -u"
- go test ./...
- acceptance/scripts/run_test.sh -a
branches:
  only:
  - master
  - production
  - staging-alpha
before_deploy:
- export BUILD_INFO=build-$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d-%H-%M-%S")-$TRAVIS_BUILD_NUMBER
# Extract any encrypted env vars and put them into the manifests/manifest-master.yml
- python deploy/travis-vars-to-manifest.py
# Download the go-bindata binary, which is necessary for the CF CLI
- go get -u github.com/jteeuwen/go-bindata/...
- export GOBINDATA_BIN=$(which go-bindata)
- export PATH=$GOBINDATA_BIN:$PATH
- echo $GOBINDATA_BIN
# Download the autopilot binary
- go get -u github.com/concourse/autopilot
- export GOAUTOPILOT_BIN=$(which autopilot)
- export PATH=$GOAUTOPILOT_BIN:$PATH
# Make sure we can execute the deploy script.
- chmod a+x deploy/travis_deploy.sh
# Download the CF CLI Soruce files
- export CLIPATH=$HOME/gopath/src/github.com/cloudfoundry/cli
- export GOPATH=$HOME/gopath/$CLIPATH/Godeps/_workspace:$HOME/gopath
- mkdir -p $CLIPATH
- git clone --branch v6.12.3 https://github.com/cloudfoundry/cli.git $CLIPATH
# Build the CF CLI
- chmod a+x deploy/prepare_deploy.sh
- deploy/prepare_deploy.sh
deploy:
- provider: script
  skip_cleanup: true
  script: deploy/travis_deploy.sh
  on:
    branch:
    - master
    - production
    - staging-alpha
env:
  global:
  - TRAVIS_NODE_VERSION="4.2.3"
  - CF_API=https://api.cloud.gov
  - CF_ORGANIZATION=cf
  - CONSOLE_UAA_URL=https://uaa.cloud.gov/
  - CONSOLE_API_URL=https://api.cloud.gov/
  - CONSOLE_LOG_URL=https://loggregator.cloud.gov/
  - CONSOLE_LOGIN_URL=https://login.cloud.gov/
  - CONSOLE_HOSTNAME=http://localhost:9999/
  - CONSOLE_TEST_ORG_NAME=CF-DECK-TESTING
  - CONSOLE_TEST_SPACE_NAME=testSpace01
  - CONSOLE_TEST_APP_NAME=testapp01
  - CONSOLE_TEST_HOST=testtestroute1
  - CONSOLE_TEST_DOMAIN=apps.cloud.gov
  - secure: xn/EXShpj51D9TTQgwrOj5H3c7gr41i+KnoOesfJDc1twY4reS8bWIBZU1zq2xaMsA8sus97Byk5MSXKifIzO5Gk6nyKzBo1z0HIXhpAVBy8RwNpLvUZrjrtz/24FmeQWs7McIfPZ92UWsGTI0BGVsSbIeAzeAkwIXb0/M1HUG4r7wgEOF+dlr3pYOtQBJ45wsst+n1RzUbWyHP7UPCcNHSrI7Q1y4odtK0MLMIozWBm5TbhpJnN4ylQCVPg2077Bsb5emg0G1K2Gfplhzvsu2+1BOekBHBsA4MJIPA1Y4dB2rkHeRvWgIyjg+w+wDyq0Kd4yP5Kku/N1U2b1llaOOLNABGYmfkteFgugHv73xfPoN2uLRIrWOpxywp+r/7qVDO8s5ZjjAGQfnFql53JBxD7/eAKH4sqaR5uW1uSpwpAmjaNAa7wcmgFKi0nyFovIBgbTH37M8nSDIS6/YfYYRiGMQA3piiUvBqVFpguSDrgup8/O8KsMn2SfPLvk7GG5bb8JOO0dWzXFuq1CWSzU4cIvcYfVkwmOKjpvKXYX1ebZz3T7i+ZL1fijQKFMlzpQGNPqHZJ/QwjH45G+Nw8Cz4waxP8l4C4ros5rIgR6CdYoRqfrhGMODum/JmoChM85hVbZbRw0AMJ+mRgprqDkru1AGSeBrxxSnwmX6eS0bs=
  - secure: GJ6iBRZ0NAw9d/RxA0BjyIRawDYUd5oVPRSEvmRWzxjw+eghBCKgp/K3RW7D6hbKUJTJ/A95Tm1cy74OgUffMkD5q5I6AJaf0LHp5rNSVP5Izu0ewbh95UE6WbFhytJjLu0Qsl0uW9v5/omG4Qm7odvvnWGO8yGDJpAbO+rMG1I09puy8n5QNESuUX0pwJKsQ1E/3uHwPfhFUacKl0bFHIEM8hLA9FWV5pl5p+cbx3fAU4U6hajB9Pur9zlRWb88nFOjrDE86RpA6Ihcu6qWERmOz441NWinUfGoLZruWp4YVhErZVp2KcOpMWyl5ObQ8Bu8JWyT9tGInyI9KPO+b5UI7i1jUkRJyQT2/snRdWcvYMWPe7gyQMz8VIogR/UUGOCBUGFm2+N03cb+UV8NxfSuR7IruX+8fWw0HvL02QYGWB1pTbebpdwn+V/ZO0+6DrOn62BVpxVqE8mNVS9Z2927GDsXRBA/C/KAHK6zaa1Vk5ADCDCFe3meysBp6BIWXKRDlnXgsomQzjAZ+Ri5us5zPWYQnIjvbJGUwXOpcFn7HiAQf0JzhvTb6s1F64Lr9yk82+rqtMSf5H3WW6yaJUirGtxlb1McD4BnsIH7F/C0ALJdZy35ZCKFhvFbGdsBeZGl6AYIuNqKz3r5U6gYycrRQ+/lGftVVRUTk90gR8A=
  - secure: UoTc2R1pw6IAzshPFBpn2nQfwfoCtO/e7kTk2yr6WEOH3znWgSULibFw8pe6updsd+byyxSrFFZXk7H5b5qY8lWiWkOm3L5o9Aj2/h2+m2ayo7HeeXMc3YiPW8guRz0wS+jTGkquA0KESyNZpruZO5BJ7lT8iylNiaFhdTYUZHXkvZbdNsmQB+ggM2+TYMQQOQ3ncUdmwZUUkRGxeVHYC2/nhDMRxvv8gZ2GD9CkUW0/Y/zVvjmm/fObAPpJk/XU1sdOs3KDqbnDRswpcZ/MPAsTS8seVXUwEgPnqUGV8E1y31CpXtE4jOyFASKyt9VcSyI8mMjEVo62JwpLWbVs//Bh/40bavfsnU1zoRGpm9gF9X3Mgb27Ua1YWzBmrrlrzHlZD8HImvYB+nZ9hpbrnX4f8H4W6arJAqcw8RKOagrXEgyUUCvXbK0HtbsfFkSjeiO3/zQo6MgaJ906o978Ws2LkOlqEasOPFhBgzPMCO7NWsHIWMCnuK1/wkp7BrhMKmnOgOR6M6z2esBOsYOgXOhzSsno4FZY6tXYGo9V+oicVBhSsulSpT/wfIablc0kSc0fGlWxEVqM2k7zP28Q4aY0L9PAERjCz1oqWwMUdVP01e4fAekHhjwwJsmnlEqOGZ4jRY4ClGl85ldtynwXyafvd7i2jSujXXtMY2TK7/0=
  - secure: LQpGKyz92BeWpaKoaDbC13miCOO6rZAE89WffXLaIfwn3HlyvYJ4bvmCpRvFzx/fd8iyY54pc9s8+wO0jdxUJpyE9Bxb8W9m9VjbAZL87uGaoAbz4Y1IPshqE24M12ggoaML9cSeAHfj/Df6fby09lJStnKXNxAt1K8nXe79OQyhBOMnFQYt6av+H0g6gZxVWTlKyFSbKogbEZ7B66ttO8KL+Ijfrba32dZUU5nHGYFWSaYHeChH/n3u9fXwdWImb7UBnjP1jrEDTeiAjJu4y/Jyp7SDmPeIb1mIHplywurhqz1oYeyngxjDpsxDCho9g28UextC0J/Vhwk+ClbH1Y6XX1Si6tSOHghsu+UaTNlwElra0rqKwnI21MRwRMeQkSd9rmQ4xW3BJDG2t8RtL5wV/WUycNueMubPr8NxkGsh9IDbQZ98xCOqyr8xX9MMixeKYZAS2dHNG0yq2dCAnMDGB8yhJiig7WuMPQ6D47yTY1pLJPuU5nG63au0YwH0FzNEnW6aK/IesqL4OF8L1W+iCOuYYEsigHvbL7CZ2NE0rVPI96p47ASj0UbUuueD8BiOJCBGf2CHVDfCNTtyNpEF9i4L/yE9dj0RpDMzCgEc3bzOEG8MW6sefFC4hF95kxD3yoeVhFzo2R8FMxEsRqMntBvF6tqueeVaZD2ihvE=
  - secure: e6nb3z9KvZHazGabWnUXOXxEe8qYmqS7Hbm7Az5wuUFFh50aI77Ie78LTgKVIak87lZv5nSWCK1YY8N5dGf1i3ZPha/wfvjYXcpNjFdOq58LsOAVF+YcT+we27OqNyzsBD2dt/O5jHAXneYEysBPwVs8gH7FtaQGq3+nUFrWcPX8aYY8BeMb323Zqf9y7O3E6KsCVemZpJbLCWKclCvL0/g5vbI8BO57IYI+GGx92OURDM4Y3GA15pWqlaXrl5MdOr9zCnd/QzrDzQIyQFHEDA67+sTz1th6i+7Uh5N6ABJkjcebw+8f4Y7l3Vo3L/P0TW0yPwdkPE8YFIxc7Tdzk+ZhBf+6aORBYH09HlAEj8vmJCcazF4KtKXl6mqElCFO8OXQ/IUtJ+l0UhWGIEQMCKrmEazn0ayZjHakZToFskJeW5HZwaXrr9jxlHhriP+/b9v0VpULRV7aYGmNauWmfQQEwjFz0ox9AZTzplw/9PCYpck+PDNfZ8rEk9Qdqxk5Z/ALPqHpdxpwe2QB6q64JniIGKQ+mc2J2fSRuTgGdy7d/HBiU3uzPydfE0ea14SVn8/OWx7ifsu6scfGwQlBwvWnRaIiOZn70hsxEWcBj5C8CdEDLbjz2JG4URGzBmz4b1tZrOuyK9utL/NfFDxA+0a46UYDHMe9YwnpVIznEg8=
