version: '2'
services:
  app:
    extends:
      file: docker-services.yml
      service: base_app
    command: npm run testing-server
    ports:
    - 8001:8001
  watch:
    extends:
      file: docker-services.yml
      service: base_app
    command: npm run watch
  watch_cg_style:
    extends:
      file: docker-services.yml
      service: base_app
    working_dir: /cg-style
    command: npm run watch
volumes:
  node-modules:
  cg-style-node-modules:
  npm-cache:
  global-node-modules:
