version: '2'
services:
  app:
    build: .
    volumes:
    - .:/usr/src/app
    - node-modules:/usr/src/app/node_modules/
    command: npm run testing-server
    environment:
    - PORT=8001
    ports:
    - 8001:8001
  build:
    build: .
    volumes:
    - .:/usr/src/app
    - node-modules:/usr/src/app/node_modules/
    command: npm run watch
volumes:
  node-modules:
