version: '2'
services:
  app:
    build: .
    volumes:
    - nvm:/cg-dashboard/.nvm
    - node-modules:/cg-dashboard/node_modules
    - .:/cg-dashboard
    command: npm run testing-server
    ports:
    - 8001:8001
  watch:
    build: .
    volumes:
    - nvm:/cg-dashboard/.nvm
    - node-modules:/cg-dashboard/node_modules
    - .:/cg-dashboard
    command: npm run watch
volumes:
  node-modules:
  nvm:
