---
version: 2
jobs:
  build:
    working_directory: ~/18F/cg-dashboard
    shell: /bin/bash --login
    environment:
      GODIST: go1.9.linux-amd64.tar.gz
      WS: /home/ubuntu/.go_workspace/src/github.com/18F/cg-dashboard
      CF_ORGANIZATION: cloud-gov
    docker:
    - image: circleci/golang:1.9.7-stretch-node-browsers
    steps:
#    - checkout
    - run:
        working_directory: ~/18F/cg-dashboard
        command: nvm install && nvm use && nvm alias default $(cat .nvmrc)
    - run:
        working_directory: ~/18F/cg-dashboard
        command: mkdir -p download
    - run:
        working_directory: ~/18F/cg-dashboard
        command: test -e download/$GODIST || curl -o download/$GODIST https://storage.googleapis.com/golang/$GODIST
    - run:
        working_directory: ~/18F/cg-dashboard
        command: sudo rm -rf /usr/local/go
    - run:
        working_directory: ~/18F/cg-dashboard
        command: sudo tar -C /usr/local -xzf download/$GODIST 
