---
version: 2
jobs:
  build:
    working_directory: ~/18F/cg-dashboard
    parallelism: 1
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
      GODIST: go1.9.linux-amd64.tar.gz
      WS: /home/ubuntu/.go_workspace/src/github.com/18F/cg-dashboard
      CF_ORGANIZATION: cloud-gov
    docker:
    - image: circleci/golang:1.9.7-stretch-node-browsers
    steps:
    - checkout
    - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS    
    - run:
        working_directory: ~/18F/cg-dashboard
        command: nvm install && nvm use && nvm alias default $(cat .nvmrc)
    - run:
        working_directory: ~/18F/cg-dashboard
        command: mkdir -p download
    - run:
        working_directory: ~/18F/cg-dashboard
        command: test -e download/$GODIST || curl -o download/$GODIST https://storage.googleapis.com/golang/$GODIST
    - run:
        working_directory: ~/18F/cg-dashboard
        command: sudo rm -rf /usr/local/go
    - run:
        working_directory: ~/18F/cg-dashboard
        command: sudo tar -C /usr/local -xzf download/$GODIST 
    # Dependencies
    #   This would typically go in either a build or a build-and-test job when using workflows
    # Restore the dependency cache
    - restore_cache:
        keys:
        # This branch if available
        - v1-dep-{{ .Branch }}-
        # Default branch if not
        - v1-dep-master-
        # Any branch if there are none on the default branch - this should be unnecessary if you have your default branch configured correctly
        - v1-dep-
    - run: sudo apt-get update; sudo apt-get install libicu52
    - run: go version
    - run: go get -u github.com/golang/dep/cmd/dep
    - run: rm -rf $WS
    - run: mkdir -p $(dirname $WS) && ln -s $(pwd) $WS
    - run: cd $WS && dep ensure
    - run: npm install
    - run: npm run test-selenium-install
    # This is based on your 1.0 configuration file or project settings
    - run: cd $WS && go build
    - run: npm run build
    - run: wget https://chromedriver.storage.googleapis.com/2.33/chromedriver_linux64.zip
    - run: unzip chromedriver_linux64.zip
    - run: sudo cp chromedriver /usr/local/bin/chromedriver
    # Save dependency cache
    - save_cache:
        key: v1-dep-{{ .Branch }}-{{ epoch }}
        paths:
        # This is a broad list of cache paths to include many possible development environments
        # You can probably delete some of these entries
        - vendor/bundle
        - ~/virtualenvs
        - ~/.m2
        - ~/.ivy2
        - ~/.bundle
        - ~/.go_workspace
        - ~/.gradle
        - ~/.cache/bower
        # These cache paths were specified in the 1.0 config
        - node_modules
        - ./node_modules