---
buildpack: go_buildpack
memory: 256M
services:
- dashboard-ups
- dashboard-redis
env:
  GOVERSION: go1.6.3
  GOPACKAGENAME: github.com/18F/cg-dashboard
  GO15VENDOREXPERIMENT: 1
  PRODUCTION: true
  SESSION_BACKEND: redis
